manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-keyboard-torne
      url: https://github.com/TrevorVonSeggern/zmk-keyboard-torne
      revision: main
      import: west.yml
  self:
    path: config
